FROM python:3.12-slim

WORKDIR /app

# Install system dependencies WeasyPrint needs
# RUN apt-get update && apt-get install -y \
#     gcc \
#     libpango-1.0-0 \
#     libpangoft2-1.0-0 \
#     libpangocairo-1.0-0 \
#     libgdk-pixbuf2.0-0 \
#     libffi-dev \
#     libcairo2 \
#     && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "run.py"]