"""add verify token columns to recovery details

Revision ID: 01dc895093c4
Revises: b41bfa73c7c4
Create Date: 2026-04-01 00:32:04.408695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dc895093c4'
down_revision = 'b41bfa73c7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verify_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.drop_column('verify_token_expiry')
        batch_op.drop_column('verify_token')

    # ### end Alembic commands ###
