"""update product id to string, add product bundles

Revision ID: 0a5cbe2d715b
Revises: 043f6eb4b2de
Create Date: 2026-03-12 05:31:20.266957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a5cbe2d715b'
down_revision = '043f6eb4b2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductBundles',
    sa.Column('bundle_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('bundle_name', sa.String(length=100), nullable=False),
    sa.Column('bundle_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.product_id'], ),
    sa.PrimaryKeyConstraint('bundle_id'),
    sa.UniqueConstraint('product_id')
    )
    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('bundle')

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'Sales', ['transaction_id'], ['transaction_id'])

    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundle', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    op.drop_table('ProductBundles')
    # ### end Alembic commands ###
