"""add column preferences, role column settings, category threshold

Revision ID: 0b4243f6eb7f
Revises: c320ee0a69e0
Create Date: 2026-04-01 12:33:41.984043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4243f6eb7f'
down_revision = 'c320ee0a69e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inventory_product'))

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_bundle_product'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    # ### end Alembic commands ###
