"""Update product sale and defect detail to restrict delete product if have a details

Revision ID: 1839d85c1dc2
Revises: 6e968149b8de
Create Date: 2026-03-19 06:15:54.933450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1839d85c1dc2'
down_revision = '6e968149b8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.drop_column('verify_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verify_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_expiry', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('verify_token', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
