"""Add archive defects

Revision ID: 3041cde81369
Revises: 632645778407
Create Date: 2026-04-08 01:37:31.939599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3041cde81369'
down_revision = '632645778407'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Users', ['archived_by'], ['user_id'])
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('archived_by')
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_defect_detail_deleted_by'), 'Users', ['deleted_by'], ['user_id'])
        batch_op.alter_column('proposed_supplier_compensation',
               existing_type=sa.Enum('loss', 'same_item', 'different_item', 'money'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('supplier_compensation',
               existing_type=mysql.ENUM('pending', 'loss', 'same_item', 'different_item', 'money', 'none'),
               nullable=True)
        batch_op.alter_column('customer_compensation',
               existing_type=mysql.ENUM('full_refund', 'partial_refund', 'exchange_same', 'exchange_different', 'none'),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('submitted', 'active', 'rejected'),
               nullable=True)
        batch_op.alter_column('origin',
               existing_type=mysql.ENUM('in_store', 'customer'),
               nullable=True)
        batch_op.drop_column('archived_at')
        batch_op.drop_column('archived_by')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
