"""add ON UPDATE CASCADE to product FK

Revision ID: 3370ac30f172
Revises: 4dfff149e817
Create Date: 2026-03-22 05:27:26.338007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3370ac30f172'
down_revision = '4dfff149e817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Defect_Details_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inventory_product'))
        batch_op.drop_constraint(batch_op.f('Inventory_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_bundle_product'))
        batch_op.drop_constraint(batch_op.f('ProductBundles_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('Sales_Details_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Stock_In_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Stock_In_ibfk_1'), 'Products', ['product_id'], ['product_id'], ondelete='RESTRICT')

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Sales_Details_ibfk_2'), 'Products', ['product_id'], ['product_id'], ondelete='RESTRICT')
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ProductBundles_ibfk_1'), 'Products', ['product_id'], ['product_id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Inventory_ibfk_1'), 'Products', ['product_id'], ['product_id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Defect_Details_ibfk_1'), 'Products', ['product_id'], ['product_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
