"""add column preferences, role column settings, category threshold

Revision ID: 3caebfe085de
Revises: 01dc895093c4
Create Date: 2026-04-01 12:20:13.702236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caebfe085de'
down_revision = '01dc895093c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role_Column_Settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('available', sa.Text(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Column_Preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('columns', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_low_stock_threshold', sa.Integer(), nullable=False))

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inventory_product'))

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_bundle_product'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.drop_column('default_low_stock_threshold')

    op.drop_table('User_Column_Preferences')
    op.drop_table('Role_Column_Settings')
    # ### end Alembic commands ###
