"""test

Revision ID: 4c4328982f47
Revises: 0a5cbe2d715b
Create Date: 2026-03-12 05:54:59.980028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c4328982f47'
down_revision = '0a5cbe2d715b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('App_Settings')
    with op.batch_alter_table('Audit_Log', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_auditlog_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'inactive'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_defectdetail_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_defectdetail_defect'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])
        batch_op.create_foreign_key(None, 'Defects', ['defect_id'], ['defect_id'])

    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_defect_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bundle_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_category'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Categories', ['category_id'], ['category_id'])

    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recovery_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    with op.batch_alter_table('Sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_saledetail_transaction'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_saledetail_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Sales', ['transaction_id'], ['transaction_id'])
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])

    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stockin_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stockin_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['product_id'])
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Stock_In', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stockin_user'), 'Users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_stockin_product'), 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_saledetail_product'), 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_saledetail_transaction'), 'Sales', ['transaction_id'], ['transaction_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('Sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sales_user'), 'Users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recovery_user'), 'Users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_category'), 'Categories', ['category_id'], ['category_id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bundle_product'), 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inventory_product'), 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_defect_user'), 'Users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_defectdetail_defect'), 'Defects', ['defect_id'], ['defect_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_defectdetail_product'), 'Products', ['product_id'], ['product_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('active', 'inactive'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('Audit_Log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_auditlog_user'), 'Users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.alter_column('reference_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    op.create_table('App_Settings',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('user_counter', mysql.INTEGER(), server_default=sa.text("'1000'"), autoincrement=False, nullable=False),
    sa.Column('counter_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_password', mysql.VARCHAR(length=255), server_default=sa.text("'shekel123'"), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(`id` = 1)', name=op.f('single_row')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
