"""add stock adjustment request tables

Revision ID: 55a467207c93
Revises: 0b4243f6eb7f
Create Date: 2026-04-02 07:34:37.235990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a467207c93'
down_revision = '0b4243f6eb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stock_Adjustment_Requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('request_type', sa.Enum('stock_in', 'adjustment'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'partially_approved', 'rejected'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('Stock_Adjustment_Details',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.product_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['Stock_Adjustment_Requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('Stock_Adjustment_Details')
    op.drop_table('Stock_Adjustment_Requests')
    # ### end Alembic commands ###
