"""add email verification to recovery details

Revision ID: 6e968149b8de
Revises: 9da8b052940e
Create Date: 2026-03-17 23:11:57.519639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e968149b8de'
down_revision = '9da8b052940e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verify_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verify_expiry', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)

    with op.batch_alter_table('Recovery_Details', schema=None) as batch_op:
        batch_op.drop_column('verify_expiry')
        batch_op.drop_column('verify_token')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
