"""v2

Revision ID: 7f4323669c16
Revises: 4c4328982f47
Create Date: 2026-03-12 06:00:41.583992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4323669c16'
down_revision = '4c4328982f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('App_Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_counter', sa.Integer(), nullable=False),
    sa.Column('counter_year', sa.Integer(), nullable=False),
    sa.Column('default_password', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('App_Settings')
    # ### end Alembic commands ###
