"""Update admin and coadmin to superadmin and admin

Revision ID: 86aa6cb288ae
Revises: 06c3b574442e
Create Date: 2026-03-28 10:10:29.304843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86aa6cb288ae'
down_revision = '06c3b574442e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inventory_product'))

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_bundle_product'))

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'cashier', 'stocking', 'co-admin'),
               type_=sa.Enum('superadmin', 'superadmin', 'cashier', 'stocking'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('superadmin', 'superadmin', 'cashier', 'stocking'),
               type_=mysql.ENUM('admin', 'cashier', 'stocking', 'co-admin'),
               existing_nullable=False)

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    # ### end Alembic commands ###
