"""update audit reference to string

Revision ID: cbb096346baf
Revises: a1b2c3d4e5f6
Create Date: 2026-04-11 12:30:59.514361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbb096346baf'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Audit_Log', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('Defect_Exchange_Items', schema=None) as batch_op:
        batch_op.alter_column('no_money_exchange',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('override_used',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('ix_dei_defect_detail_id'))
        batch_op.drop_index(batch_op.f('ix_dei_product_id'))

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_inventory_product'))

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_bundle_product'))

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('override_used',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               comment=None,
               existing_comment='1 when this specific line item quantity exceeded quantity_available at charge time. Does not block the sale.',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.alter_column('override_used',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               comment='1 when this specific line item quantity exceeded quantity_available at charge time. Does not block the sale.',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('ProductBundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_bundle_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_product'), ['product_id'], unique=True)

    with op.batch_alter_table('Defect_Exchange_Items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dei_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dei_defect_detail_id'), ['defect_detail_id'], unique=False)
        batch_op.alter_column('override_used',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('no_money_exchange',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('Audit_Log', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
