"""rename unit_price to cost_price, product_price to total_price

Revision ID: d0ec620eec2a
Revises: 86aa6cb288ae
Create Date: 2026-03-31 00:48:12.080690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ec620eec2a'
down_revision = '86aa6cb288ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price_at_defect', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('unit_price_at_defect')

    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_unit_price')


    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('unit_price')
        batch_op.drop_column('product_price')

    with op.batch_alter_table('Sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_unit_price')

    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False)
        batch_op.drop_column('unit_price_at_sale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sales_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_at_sale', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True)
        batch_op.drop_column('cost_price_at_sale')

    with op.batch_alter_table('Sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_cost_price')

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_price')
        batch_op.drop_column('cost_price')


    with op.batch_alter_table('Defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_cost_price')

    with op.batch_alter_table('Defect_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_at_defect', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('cost_price_at_defect')

    # ### end Alembic commands ###
